
version: "3.9"

services:
  django_app:
    container_name: django_arsmagica_seasons
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    # Port mapping — expose Django (Gunicorn) on port 8000
    ports:
      - "8000:8000"

    # Load secrets from host system
    env_file:
      - /etc/secrets/mysql/keys/.django_env

    # Add host-to-container network mapping so Django can reach MySQL running on the server
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Place container on a shared network (can be used later by Flask + Nginx)
    networks:
      - kvistholm_backend

    # Optional health check to ensure Gunicorn starts correctly
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  kvistholm_backend:
    driver: bridge
