# Generated by Django 5.2.7 on 2025-10-07 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "character_type",
                    models.CharField(
                        choices=[
                            ("Magi", "Magi"),
                            ("Companion", "Companion"),
                            ("Other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("Summer", "Summer"),
                            ("Autumn", "Autumn"),
                            ("Winter", "Winter"),
                            ("Spring", "Spring"),
                        ],
                        max_length=12,
                    ),
                ),
                ("summary", models.CharField(max_length=455)),
                ("description", models.TextField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["year", "season", "name"],
            },
        ),
    ]
