# Generated by Django 5.2.7 on 2025-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arsmagica_seasons_app", "0003_alter_seasonalwork_character_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonalwork",
            name="character_type",
            field=models.CharField(
                choices=[
                    ("Hermetic Magus", "Hermetic Magus"),
                    ("Vitki Magus", "Vitki Magus"),
                    ("Companion", "Companion"),
                    ("Other", "Other"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="seasonalwork",
            name="season",
            field=models.CharField(
                choices=[
                    ("Summer", "Summer"),
                    ("Autumn", "Autumn"),
                    ("Winter", "Winter"),
                    ("Spring", "Spring"),
                    ("Unknown", "Unknown"),
                ],
                max_length=64,
            ),
        ),
    ]
