name: Deploy Seasons

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ROOT_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            # Ensure MySQL is running.

            systemctl enable mysql
            systemctl start mysql

            # Remove old project if exists.

            cd /srv

            if [ -d "arsmagica_seasons" ]; then

               # Check if inside a virtual environment.

               cd /srv/arsmagica_seasons

               if [ -n "$VIRTUAL_ENV" ]; then
                   echo "Deactivating existing virtual environment: $VIRTUAL_ENV"
                  deactivate
               fi

               rm -rf /srv/arsmagica_seasons

            fi

            cd /srv

            # Clone repo fresh.

            git clone git@github.com:JoakimKV/arsmagica_seasons.git /srv/arsmagica_seasons

            # Copy secrets from another .env file (.django_env) into the .env file (.django_env) 
            # in the project.

            cp /etc/secrets/mysql/keys/.django_env /srv/arsmagica_seasons/.django_env

            # Install Python dependencies.
 
            cd /srv/arsmagica_seasons

            python -m venv venvdjango1
            source venvdjango1/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

            # Restart Docker app container (Django only).

            docker compose down
            docker compose --env-file /etc/secrets/mysql/keys/.django_env up -d --build django_app

            # Reload Nginx if config changed.

            nginx -t
            systemctl daemon-reload
            systemctl reload nginx

            deactivate
